feat: task artifacts
This allows you to upload local files to the remote script runner.

The following enhancements are made along with this feature mainly for testing purpose:

- templated task step arguments

```yaml
tasks:
  foo:
    parameters:
    - name: param1
    steps:
    - task: anothertask
      arguments:
        param2: '{{ get "param1" }}'
  bar:
    parameters:
    - name: param2
    script: |
      echo {{ get "param2" }}
```

- codebuild: the container image specified by `runner.image` is now applied to the codebuild project on each run

diff --git a/examples/codebuild/bin/codebuildsh b/examples/codebuild/bin/codebuildsh
--- a/examples/codebuild/bin/codebuildsh
+++ b/examples/codebuild/bin/codebuildsh
@@ -23,6 +23,7 @@ while test $# -gt 0; do
                         echo "--s3-bucket=mybucket               specify S3 bucket to store the build bundle"
                         echo "--security-groups=SG1,SG2,...      specify security groups that are associated to the builder container"
                         echo "--service-role=myiamrolename       specify the iam role used by CodeBuild"
+                        echo "--image=alpine:3.7                 specify the container image used by CodeBuild builds"
                         exit 0
                         ;;
                 -a)
@@ -53,6 +54,10 @@ while test $# -gt 0; do
                         ;;
                 --service-role*)
                         export iamrole=`echo $1 | sed -e 's/^[^=]*=//g'`
+                        shift
+                        ;;
+                --image*)
+                        export image=`echo $1 | sed -e 's/^[^=]*=//g'`
                         shift
                         ;;
                 *)
@@ -88,6 +93,7 @@ vpcid=${vpcid:-myvcpid}
 # Requires NAT gateway and corresponding route table to access the internet
 subnets=${subnets:-subnet-12345678}
 sgids=${sgids:-sg-12345678}
+image=${image:-alpine:3.7}
 vpcconfig=vpcId=$vpcid,subnets=$subnets,securityGroupIds=$sgids
 
 projects=$(aws codebuild batch-get-projects --names $name)
@@ -95,7 +101,16 @@ projects=$(aws codebuild batch-get-projects --names $name)
 num_projects=$(jq '.projects | length' <(echo "$projects"))
 
 if [ "$num_projects" -gt 0 ]; then
-  jq '.projects[0]' <(echo "$projects") > project.json
+  #jq '.projects[0]' <(echo "$projects") > project.json
+  aws codebuild update-project \
+    --name $name \
+    --description "$desc" \
+    --source type=S3,location=$location \
+    --service-role $iamrole \
+    --vpc-config $vpcconfig \
+    --artifacts type=NO_ARTIFACTS \
+    --environment type=LINUX_CONTAINER,image=${image},computeType=BUILD_GENERAL1_SMALL | tee create-project.json 1>&2
+  jq .project create-project.json > project.json
 else
   # See the official doc for the details of the params: https://docs.aws.amazon.com/codebuild/latest/userguide/run-build.html#run-build-cli
   aws codebuild create-project \
@@ -105,31 +120,52 @@ else
     --service-role $iamrole \
     --vpc-config $vpcconfig \
     --artifacts type=NO_ARTIFACTS \
-    --environment type=LINUX_CONTAINER,image=alpine:3.7,computeType=BUILD_GENERAL1_SMALL | tee create-project.json
+    --environment type=LINUX_CONTAINER,image=${image},computeType=BUILD_GENERAL1_SMALL | tee create-project.json 1>&2
   jq .project create-project.json > project.json
 fi
 
+# create the source archive
+
 mkdir -p codebuildwork
 rm -rf codebuildwork/*
-rm test.zip
+
+# stdbuf is necessary. otherwise you get stdout/stderr mixed in the stdout captured by variant
+# See https://superuser.com/a/770612 for more details on the stdbuf usage
 cat <<EOF > codebuildwork/buildspec.yml
 version: 0.2
 env:
-  varialbles:
+  variables:
     build_version: "0.1" 
 phases:
   build:
     commands:
-    - |
+    - stdbuf -i 0 -o 0 -e 0 ./build.sh
+EOF
+
+cat <<EOF > codebuildwork/build.sh
+#!/usr/bin/env bash
+
+exec 3>&2 2> >(sed 's/^/variant.stderr: /' 1>&3)
+
 EOF
 echo "$script" | while read LINE || [ -n "${LINE}" ]; do
-  echo "      ${LINE}" >> codebuildwork/buildspec.yml
+  echo "$LINE" >> codebuildwork/build.sh
 done
+chmod +x codebuildwork/build.sh
+
 pushd codebuildwork 1>&2
+if [ -f test.zip ]; then
+  rm test.zip
+fi
 zip -r ../test.zip * 1>&2
 popd 1>&2
 
 aws s3 cp test.zip s3://$location 1>&2
+
+if ! aws s3 cp test.zip s3://$location 1>&2; then
+  echo "failed to upload the build source archive. perhaps you're missing aws api connectivity?" 1>&2
+  exit 1
+fi
 
 aws codebuild start-build --project-name $(cat project.json | jq -r .name) > start-build.json
 
@@ -157,11 +193,11 @@ build_status() {
   jq -r .buildStatus build.json 1>&2
   jq .phases build.json 1>&2
   aws logs get-log-events --log-group-name $log_group_name --log-stream-name $log_stream_name > log-events.json
-  jq -jr '.events[] | select(true) | .message' log-events.json | sed -n '/Running command/,$p' | sed '1,2d' | $reverse | sed -n '/Phase complete: BUILD/,$p' | sed '1,2d' | $reverse
+  jq -jr '.events[] | select(true) | .message' log-events.json | sed -n '/Running command/,$p' | sed '1d' | $reverse | sed -n '/Phase complete: BUILD/,$p' | sed '1d' | $reverse
 }
 
 while build_in_progress; do
-  sleep 1
+  sleep 5
 done
 
 build_status
